import React from 'react';

const Footer: React.FC = () => {
    return (
        <footer className="bg-dark-900 border-t border-white/10 py-12">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                <p className="font-display text-xl text-white italic mb-4">
                    BOUDEN <span className="text-red-600">MOTORSPORT</span>
                </p>
                <div className="flex justify-center space-x-6 mb-8 text-gray-400 text-sm">
                    <a href="#" className="hover:text-white transition-colors">Privacy Policy</a>
                    <a href="#" className="hover:text-white transition-colors">Terms of Service</a>
                    <a href="#" className="hover:text-white transition-colors">API Status</a>
                </div>
                <p className="text-gray-600 text-sm">
                    © 2025 Bouden Motorsport. All data is generated by Gemini AI for demonstration purposes.
                </p>
            </div>
        </footer>
    );
};

export default Footer;